### ISSUE TITLE
Can poplddecay properly handle autotetraploid genotypes?

### ISSUE THREAD

**Issue by HongboDoll** [hewm2008/PopLDdecay#2]
Dear Dr. He,

Thanks for developing this helpful software. I have a gatk vcf file with autotetraploid SNP genotypes. I tried poplddecay on this vcf and it turned out to filter a large array of SNPs, leaving only minor proportion of markers for computing r-square. So can poplddecay properly handle autotetraploid genotypes? If it doesn't, do you know some other methods that can do this? 

Thanks in advance,

**Comment by hewm2008** [comment]
Dear HongboDoll
These two softwares were developed based on diploidy， and can support allopolyploidy such as wheat (AABBDD).  but autopolyploids for example  [triploidy (AAABBB) or  is other]  not applicable.
sorry  for these two software can't help you.     you can see this paper   https://link.springer.com/article/10.1007/s00122-016-2798-8

**Comment by HongboDoll** [comment]
> Dear HongboDoll These two softwares were developed based on diploidy， and can support allopolyploidy such as wheat (AABBDD). but autopolyploids for example [triploidy (AAABBB) or is other] not applicable. sorry for these two software can't help you. you can see this paper https://link.springer.com/article/10.1007/s00122-016-2798-8

Hi,

Thanks for your quick reply!
